### ISSUE TITLE
Reasons for new v1.0.0 and plans for v0.0.5

### ISSUE THREAD

**Issue by cytham** [chenying2016/queries#21]
May I know the reasons for the major change from v0.0.5 to v1.0.0? 
And will support for v0.0.5 be continued? 

Will v1.0.0 also has the blast table 6 output as before? 

As pipelines and tools may rely on your v0.0.5, I would hope that you will still continue support for v0.0.5 and create a separate repo for your new version of v1.0.0 which is quite different.

Thanks

**Comment by chenying2016** [comment]
v0.0.5 must work along with the window_masker, otherwise the fmd-index will run rather inefficiently. Window masker may mask out most of the sequence and sometimes mask out the whole sequence.  The FMD-index in v0.0.5 is built for the whole database, which requires a large amount of main memory for large database.  The biggest drawback of fmd-index is that it only applies for sequences that contains no or little repetitive subsequences. Masking out these regions has a great influence on the searching sensitivity. 

v1.0.0 supports both table 6 and table 7.

The fmd-index is replaced by a simple hash table in v1.0.0 and the window masker is not used. This simplifies the use.  Actually the use of v1.0.0 is now much simpler.   

The code of v0.0.5 is still given and maintained here.

**Comment by cytham** [comment]
@chenying2016 Sounds good, will try to accommodate these changes. 

And I do hope that the new version will be available on conda too. Thanks
